#!/usr/bin/python3
"""Factorize as many numbers."""

import sys
import math


def factorize_number(number):
    """Factorize a number into a product of two smaller numbers.
    Args:
        number (int): The number to factorize.
    Returns:
        tuple: A tuple containing the two factors.
    """
    for i in range(2, int(math.sqrt(number)) + 1):
        if number % i == 0:
            q = i
            break
    for j in range(2, int(math.sqrt(number)) + 1):
        if (number // i) * q == number:
            p = number // i
            break
    return p, q


def main():
    try:
        file_object = open(sys.argv[1], "r")
    except IndexError:
        print("Usage: ./factors <file>")
        exit()

    numbers = file_object.readlines()
    file_object.close()

    for num in numbers:
        number = int(num.rstrip("\n"))
        factors = factorize_number(number)
        print("{}={}*{}".format(number, factors[0], factors[1]))


if __name__ == "__main__":
    main()
